// flow-typed signature: d62daba2e581e024cfe3f8889bdc9c0d
// flow-typed version: <<STUB>>/jest_v^21.2.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest' {
  declare module.exports: any;
}
